FROM python:3.11-slim

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    texlive-latex-base \
    texlive-latex-extra \
    texlive-fonts-recommended \
    texlive-science \
    dvipng \
    ghostscript && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Оставим только для теста — не копируем requirements
CMD ["echo", "LaTeX packages installed successfully"]