# Use your pre-built base image
# Dockerfile.bot
# We reference the image we build in the CI
FROM ghcr.io/ackrome/matplobbot-base-python:latest

WORKDIR /app

# Copy Alembic config
COPY alembic.ini .
COPY alembic/ ./alembic/

# Copy shared lib and install it (Local code install is fast)
COPY shared_lib/ /shared_lib/
COPY setup.py /
RUN pip install --no-cache-dir /

# Copy Bot Code
COPY bot/ /app/bot/

CMD ["python3", "-m", "bot.main"]