pipeline { // Jenkinsfile for Matplobbot Deployment
    agent any

    parameters {
        string(name: 'BOT_IMAGE_TAG', defaultValue: 'latest', description: 'Docker image tag for the bot')
        string(name: 'API_IMAGE_TAG', defaultValue: 'latest', description: 'Docker image tag for the API')
        string(name: 'SCHEDULER_IMAGE_TAG', defaultValue: 'latest', description: 'Docker image tag for the scheduler')
    }

    environment {
        // Securely bind Jenkins credentials to environment variables for this job
        PROD_BOT_TOKEN      = credentials('PROD_BOT_TOKEN')
        PROD_ADMIN_USER_IDS  = credentials('PROD_ADMIN_USER_IDS')
        PROD_GITHUB_TOKEN   = credentials('PROD_GITHUB_TOKEN')
        PROD_POSTGRES_USER  = credentials('PROD_POSTGRES_USER')
        PROD_POSTGRES_PASSWORD = credentials('PROD_POSTGRES_PASSWORD')
        PROD_POSTGRES_DB    = credentials('PROD_POSTGRES_DB')
        // The DATABASE_URL will be constructed from the variables above.
        // The host is 'postgres' (the service name in docker-compose.prod.yml).
        PROD_DATABASE_URL   = "postgresql://${PROD_POSTGRES_USER}:${PROD_POSTGRES_PASSWORD}@postgres:5432/${PROD_POSTGRES_DB}"
    }

    stages {
        stage('Deploy to Production') {
            steps {
                script {
                    // Use sshagent to securely connect to the production server
                    sshagent(credentials: ['app-vm-ssh-key']) {
                        // Stage 1: Update the repository on the remote server to get the latest docker-compose.prod.yml and deploy.sh
                        sh "ssh -o StrictHostKeyChecking=no root@app-vm.panthera-banjo.ts.net 'cd ~/matplobbot && git pull'"
                        
                        // Stage 2: Securely write the .env file on the remote server using a 'heredoc'
                        sh """
                        ssh -o StrictHostKeyChecking=no root@app-vm.panthera-banjo.ts.net "cat > ~/matplobbot/.env" <<EOF
                        # This file is generated by the Jenkins CI/CD pipeline
                        BOT_TOKEN=${PROD_BOT_TOKEN}
                        ADMIN_USER_IDS=${PROD_ADMIN_USER_IDS}
                        GITHUB_TOKEN=${PROD_GITHUB_TOKEN}
                        POSTGRES_USER=${PROD_POSTGRES_USER}
                        POSTGRES_PASSWORD=${PROD_POSTGRES_PASSWORD}
                        POSTGRES_DB=${PROD_POSTGRES_DB}
                        DATABASE_URL=${PROD_DATABASE_URL}
                        EOF
                        """
                        // Stage 2: clear docker build cache
                        sh "ssh -o StrictHostKeyChecking=no root@app-vm.panthera-banjo.ts.net 'docker system prune --all --force'"
                        // Stage 3: Run the deployment script, which will now use the new .env file
                        sh "ssh -o StrictHostKeyChecking=no root@app-vm.panthera-banjo.ts.net 'cd ~/matplobbot && ./deploy.sh ${params.BOT_IMAGE_TAG} ${params.API_IMAGE_TAG} ${params.SCHEDULER_IMAGE_TAG}'"
                    }
                }
            }
        }
    }
    post {
        always {
            echo 'Deployment finished.'
        }
    }
}