pipeline {
    agent any

    parameters {
        string(name: 'BOT_IMAGE_TAG', defaultValue: 'latest', description: 'Docker image tag for the bot')
        string(name: 'WORKER_IMAGE_TAG', defaultValue: 'latest', description: 'Docker image tag for the worker') // <--- NEW
        string(name: 'API_IMAGE_TAG', defaultValue: 'latest', description: 'Docker image tag for the API')
        string(name: 'SCHEDULER_IMAGE_TAG', defaultValue: 'latest', description: 'Docker image tag for the scheduler')
    }

    environment {
        // (Environment variables remain the same)
        PROD_BOT_TOKEN      = credentials('PROD_BOT_TOKEN')
        PROD_ADMIN_USER_IDS = credentials('PROD_ADMIN_USER_IDS')
        PROD_GITHUB_TOKEN   = credentials('PROD_GITHUB_TOKEN')
        PROD_POSTGRES_USER  = credentials('PROD_POSTGRES_USER')
        PROD_POSTGRES_PASSWORD = credentials('PROD_POSTGRES_PASSWORD')
        PROD_POSTGRES_DB    = credentials('PROD_POSTGRES_DB')
        PROD_DATABASE_URL   = "postgresql://${PROD_POSTGRES_USER}:${PROD_POSTGRES_PASSWORD}@postgres:5432/${PROD_POSTGRES_DB}"
        // Redis URL might be needed if you connect externally, but usually internal docker network handles it.
        // If needed: PROD_REDIS_URL = "redis://redis:6379/0" 
    }

    stages {
        stage('Deploy to Production') {
            steps {
                script {
                    withCredentials([sshUserPrivateKey(credentialsId: 'app-vm-ssh-key', keyFileVariable: 'SSH_KEY_FILE', usernameVariable: 'SSH_USER')]) {
                        
                        sh 'chmod 600 $SSH_KEY_FILE'

                        // 1. Update repo
                        sh "ssh -i $SSH_KEY_FILE -o StrictHostKeyChecking=no root@app-vm.panthera-banjo.ts.net 'cd ~/matplobbot && git pull'"
                        
                        // 2. Create .env
                        // Added REDIS_URL just in case it is needed by apps expecting it in .env
                        sh """
                        ssh -i $SSH_KEY_FILE -o StrictHostKeyChecking=no root@app-vm.panthera-banjo.ts.net "cat > ~/matplobbot/.env" <<EOF
# Generated by Jenkins
BOT_TOKEN=${PROD_BOT_TOKEN}
ADMIN_USER_IDS=${PROD_ADMIN_USER_IDS}
GITHUB_TOKEN=${PROD_GITHUB_TOKEN}
POSTGRES_USER=${PROD_POSTGRES_USER}
POSTGRES_PASSWORD=${PROD_POSTGRES_PASSWORD}
POSTGRES_DB=${PROD_POSTGRES_DB}
DATABASE_URL=${PROD_DATABASE_URL}
REDIS_URL=redis://redis:6379/0
EOF
                        """
                        
                        // 3. Prune
                        sh "ssh -i $SSH_KEY_FILE -o StrictHostKeyChecking=no root@app-vm.panthera-banjo.ts.net 'docker system prune --all --force'"
                        
                        // 4. Deploy command
                        // Passed WORKER_IMAGE_TAG as the 4th argument
                        sh "ssh -i $SSH_KEY_FILE -o StrictHostKeyChecking=no root@app-vm.panthera-banjo.ts.net 'cd ~/matplobbot && ./deploy.sh ${params.BOT_IMAGE_TAG} ${params.API_IMAGE_TAG} ${params.SCHEDULER_IMAGE_TAG} ${params.WORKER_IMAGE_TAG}'"
                    }
                }
            }
        }
    }
    post {
        always {
            echo 'Deployment finished.'
        }
    }
}