"""add calendar_secret

Revision ID: 2fbd4aaae764
Revises: e9b6a77c5133
Create Date: 2026-03-03 17:02:04.125850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fbd4aaae764'
down_revision: Union[str, Sequence[str], None] = 'e9b6a77c5133'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('calendar_secret', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'users', ['calendar_secret'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'calendar_secret')
    # ### end Alembic commands ###
