"""Initial migration

Revision ID: 3145f2fc0295
Revises: 
Create Date: 2025-11-27 12:13:40.490639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3145f2fc0295'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat_settings', 'settings',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('discipline_short_names', 'full_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('discipline_short_names', 'short_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('latex_cache', 'formula_hash',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('latex_cache', 'image_url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('user_actions', 'action_type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('user_actions', 'action_details',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('user_favorites', 'code_path',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_constraint(op.f('user_favorites_user_id_code_path_key'), 'user_favorites', type_='unique')
    op.create_unique_constraint('uq_user_favorites_path', 'user_favorites', ['user_id', 'code_path'])
    op.alter_column('user_github_repos', 'repo_path',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_constraint(op.f('user_github_repos_user_id_repo_path_key'), 'user_github_repos', type_='unique')
    op.create_unique_constraint('uq_user_repos_path', 'user_github_repos', ['user_id', 'repo_path'])
    op.alter_column('user_schedule_subscriptions', 'entity_type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('user_schedule_subscriptions', 'entity_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('user_schedule_subscriptions', 'entity_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('user_schedule_subscriptions', 'last_schedule_hash',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_constraint(op.f('user_schedule_subscriptions_chat_id_entity_type_entity_id_n_key'), 'user_schedule_subscriptions', type_='unique')
    op.create_unique_constraint('uq_schedule_subs', 'user_schedule_subscriptions', ['chat_id', 'entity_type', 'entity_id', 'notification_time'])
    op.alter_column('users', 'username',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('users', 'full_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('users', 'avatar_pic_url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('users', 'settings',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'settings',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('users', 'avatar_pic_url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'full_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('users', 'username',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint('uq_schedule_subs', 'user_schedule_subscriptions', type_='unique')
    op.create_unique_constraint(op.f('user_schedule_subscriptions_chat_id_entity_type_entity_id_n_key'), 'user_schedule_subscriptions', ['chat_id', 'entity_type', 'entity_id', 'notification_time'], postgresql_nulls_not_distinct=False)
    op.alter_column('user_schedule_subscriptions', 'last_schedule_hash',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('user_schedule_subscriptions', 'entity_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('user_schedule_subscriptions', 'entity_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('user_schedule_subscriptions', 'entity_type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint('uq_user_repos_path', 'user_github_repos', type_='unique')
    op.create_unique_constraint(op.f('user_github_repos_user_id_repo_path_key'), 'user_github_repos', ['user_id', 'repo_path'], postgresql_nulls_not_distinct=False)
    op.alter_column('user_github_repos', 'repo_path',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint('uq_user_favorites_path', 'user_favorites', type_='unique')
    op.create_unique_constraint(op.f('user_favorites_user_id_code_path_key'), 'user_favorites', ['user_id', 'code_path'], postgresql_nulls_not_distinct=False)
    op.alter_column('user_favorites', 'code_path',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('user_actions', 'action_details',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('user_actions', 'action_type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('latex_cache', 'image_url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('latex_cache', 'formula_hash',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('discipline_short_names', 'short_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('discipline_short_names', 'full_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('chat_settings', 'settings',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    # ### end Alembic commands ###
