"""add selected_modules

Revision ID: 486390ab3824
Revises: c7a670795f42
Create Date: 2026-02-10 00:07:56.557676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '486390ab3824'
down_revision: Union[str, Sequence[str], None] = 'c7a670795f42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_schedule_subscriptions', sa.Column('selected_modules', sa.JSON(), server_default='[]', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_schedule_subscriptions', 'selected_modules')
    # ### end Alembic commands ###
