"""web_user_telegram

Revision ID: 67dcbf985963
Revises: 33b223ee15b9
Create Date: 2026-03-30 16:15:11.120535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67dcbf985963'
down_revision: Union[str, Sequence[str], None] = '33b223ee15b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('web_users', sa.Column('telegram_id', sa.BigInteger(), nullable=True))
    op.add_column('web_users', sa.Column('role', sa.String(), server_default='user', nullable=False))
    op.alter_column('web_users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('web_users', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_unique_constraint(None, 'web_users', ['telegram_id'])
    op.create_foreign_key(None, 'web_users', 'users', ['telegram_id'], ['user_id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'web_users', type_='foreignkey')
    op.drop_constraint(None, 'web_users', type_='unique')
    op.alter_column('web_users', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('web_users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('web_users', 'role')
    op.drop_column('web_users', 'telegram_id')
    # ### end Alembic commands ###
