"""add_build_cache

Revision ID: a0b5a060b6fe
Revises: d7a2abf3448f
Create Date: 2026-04-02 18:52:03.600438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0b5a060b6fe'
down_revision: Union[str, Sequence[str], None] = 'd7a2abf3448f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('build_cache', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'build_cache')
    # ### end Alembic commands ###
