"""add discipline_modules

Revision ID: e9b6a77c5133
Revises: 486390ab3824
Create Date: 2026-02-10 01:20:05.511888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9b6a77c5133'
down_revision: Union[str, Sequence[str], None] = '486390ab3824'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discipline_modules',
    sa.Column('discipline_name', sa.String(), nullable=False),
    sa.Column('module_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('discipline_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('discipline_modules')
    # ### end Alembic commands ###
