/* Studio workflow UI; uses the authenticated transport/session owned by studio.js. */
window.MpbStudioUX = (() => {
    const tr=(key,params={})=>window.MpbUI.t(key,params);
    const button=(text,action,kind='')=>{const el=document.createElement('button');el.type='button';el.className=`ui-button ${kind}`;if(typeof text==='object'){el.dataset.i18n='ux.'+text.key;el.textContent=tr(text.key);}else el.textContent=text;el.addEventListener('click',()=>run(async()=>{el.disabled=true;try{await action();}catch(error){const dialog=[...document.querySelectorAll('dialog[open]')].at(-1);if(!dialog)throw error;let status=dialog.querySelector('.dialog-error');if(!status){status=document.createElement('p');status.className='dialog-error plan-field-error';status.setAttribute('role','alert');dialog.querySelector('h2').after(status);}status.textContent=error.message||t('requestFailed');}finally{el.disabled=false;}}));return el;};
    let importDraft=null,uploadQueue=[],uploadBusy=false,uploadProjectId=null;
    function filename(){return (projectsList.find(p=>String(p.id)===String(currentProjectId))?.name||editor.getValue().match(/(?:^# |\\(?:title|section)\{)([^\n}]+)/)?.[1]||tr('document')).replace(/[\\/:*?"<>|\x00-\x1f]/g,'_').trim().slice(0,100)||'document';}
    function init(){
        const toolbar=document.createElement('div');toolbar.className='studio-workflow-toolbar';toolbar.id='studio-workflow-toolbar';
        const autosave=document.createElement('span');autosave.className='ui-muted';autosave.dataset.i18n='ux.autosave';autosave.textContent=tr('autosave');toolbar.append(autosave);
        const save=button({key:'saveAsProject'},()=>{const draft={content:editor.getValue(),type:$('doc-type').value};createNewProject();importDraft=draft;$('new-project-type').value=importDraft.type;$('new-project-type').disabled=true;$('template-container').hidden=true;updateTemplateOptions();});save.id='save-as-project';toolbar.append(save);
        toolbar.append(button({key:'manageProjects'},manageProjects),button({key:'buildHistory'},history));
        for(const id of ['btn-download-pdf','btn-download-zip','btn-send-tg']){const el=$(id);el.classList.add('ui-button');el.replaceChildren();const label=document.createElement('span');label.dataset.i18n=id==='btn-download-pdf'?'studio.downloadResult':id==='btn-download-zip'?'studio.downloadZip':'studio.send';label.textContent=window.mpbI18n.t(label.dataset.i18n);el.append(label);toolbar.append(el);}
        $('navbar').after(toolbar);

        const hint=document.createElement('p');hint.className='ui-muted studio-upload-hint';hint.dataset.i18n='ux.uploadHint';hint.textContent=tr('uploadHint');$('file-list').before(hint);const queue=document.createElement('div');queue.id='studio-upload-list';queue.setAttribute('aria-live','polite');$('file-list').before(queue);
        $('job-panel').append(button({key:'cancelBuild'},cancelJob));
        const preview=document.createElement('div');preview.id='template-preview';$('new-project-template').after(preview);$('new-project-template').addEventListener('change',templatePreview);
        $('empty-state').querySelector('p').dataset.i18n='ux.previewHint';$('empty-state').querySelector('p').textContent=tr('previewHint');$('empty-state').append(button({key:'buildNow'},compileCurrent,'primary'));
        $('create-project-button').textContent=tr('newProject');
        $('error-text').before(Object.assign(document.createElement('div'),{id:'studio-error-links'}));
    }
    function mode(){if($('save-as-project'))$('save-as-project').hidden=currentMode!=='quick';}
    function resetCreate(){importDraft=null;$('new-project-type').disabled=false;$('template-container').hidden=false;}
    function draft(){return importDraft;}
    function templatePreview(){const el=$('template-preview');if(!el)return;const id=$('new-project-template').value;el.replaceChildren();el.className='template-preview '+(id==='latex_beamer'?'template-slide':'');const page=document.createElement('div');page.className='template-paper';const h=document.createElement('h3');h.textContent=tr('templateTitle.'+id);const p=document.createElement('p');p.textContent=tr('templateDescription.'+id);const lines=document.createElement('div');lines.className='template-lines';lines.setAttribute('aria-hidden','true');page.append(h,lines);el.append(page,p);}
    async function manageProjects(){
        await transition(loadProjects);const content=document.createElement('div');content.className='ui-stack';const search=document.createElement('input');search.type='search';search.className='ui-input';search.placeholder=tr('projectSearch');search.setAttribute('aria-label',tr('projectSearch'));const list=document.createElement('div');list.className='project-manager-list';content.append(search,button({key:'newProject'},()=>{document.querySelector('dialog[open]')?.close();createNewProject();},'primary'),list);
        const render=()=>{list.replaceChildren();const matches=projectsList.filter(p=>p.name.toLocaleLowerCase().includes(search.value.toLocaleLowerCase()));if(!matches.length){const p=document.createElement('p');p.className='ui-muted';p.textContent=tr('noProjects');list.append(p);}for(const project of matches){const row=document.createElement('section');row.className='project-manager-row';const open=button(project.name,async()=>{await openProject(project.id);updateModeUi();document.querySelector('dialog[open]')?.close();});open.classList.add('project-open');const meta=document.createElement('p');meta.className='ui-muted';meta.textContent=project.type;const actions=document.createElement('div');actions.className='ui-row';
            actions.append(button({key:'rename'},async()=>{const name=await MpbUI.prompt(tr('renameProject'),project.name);if(!name)return;await api(`/studio/projects/${project.id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({name})});await loadProjects();render();}),button({key:'duplicate'},async()=>{const name=await MpbUI.prompt(tr('duplicateProject'),`${project.name} — ${tr('copyName')}`);if(!name)return;await transition(async()=>{await api(`/studio/projects/${project.id}/duplicate`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name})});await loadProjects();});render();}),button({key:'delete'},async()=>{if(!await MpbUI.confirm(tr('deleteProject'),tr('deleteProjectMessage',{name:project.name})))return;await transition(async()=>{await api(`/studio/projects/${project.id}`,{method:'DELETE'});await loadProjects();if(String(currentProjectId)===String(project.id)){currentProjectId=currentFileId=null;projectFiles=[];session.open({type:'empty',content:''});setEditorContent('',true);resetPreview();renderFileList();}});render();},'danger'));row.append(open,meta,actions);list.append(row);}};search.addEventListener('input',render);render();await MpbUI.dialog({title:tr('manageProjects'),content,actions:[{label:tr('close'),value:'close'}]});
    }
    async function conflict(record){
        const content=document.createElement('div');content.className='ui-stack';const time=document.createElement('p');time.className='ui-muted';time.textContent=tr('conflictHint')+(record.draftUpdatedAt?' '+new Date(record.draftUpdatedAt).toLocaleString(window.mpbI18n.getLanguage()):'');content.append(time);
        const grid=document.createElement('div');grid.className='conflict-grid';const a=record.draftContent.split('\n'),b=record.content.split('\n');for(const [label,lines,other] of [[tr('localVersion'),a,b],[tr('serverVersion'),b,a]]){const section=document.createElement('section'),title=document.createElement('h3'),pre=document.createElement('pre');title.textContent=label;lines.forEach((text,i)=>{const line=document.createElement('span');line.className='diff-line'+(text!==other[i]?' diff-changed':'');line.textContent=`${i+1}  ${text}\n`;pre.append(line);});section.append(title,pre);grid.append(section);}content.append(grid,button({key:'downloadBoth'},()=>MpbArchive.download(MpbArchive.zip([{name:'local.txt',text:record.draftContent},{name:'server.txt',text:record.content}]),'document-versions.zip')));
        const choice=await MpbUI.dialog({title:tr('conflictTitle'),content,actions:[{label:tr('useServer'),value:'server'},{label:tr('useLocal'),value:'local',primary:true}]});if(!choice)throw new Error(tr('resolveConflict'));return choice==='local';
    }
    async function hash(content){const value=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(content));return Array.from(new Uint8Array(value),b=>b.toString(16).padStart(2,'0')).join('');}
    function remember(job){const entries=session.readValue('job-history')||[];const item={job_id:job.job_id,status:job.status,created_at:job.created_at||new Date().toISOString(),expires_at:job.expires_at,projectId:job.projectId,name:job.name||filename(),fingerprint:job.fingerprint||job.source_fingerprint};const next=[item,...entries.filter(i=>i.job_id!==job.job_id&&Date.parse(i.expires_at)>Date.now())].slice(0,20);session.storeValue('job-history',next);}
    async function history(){const content=document.createElement('div');content.className='ui-stack';const hint=document.createElement('p');hint.className='ui-muted';hint.textContent=tr('historyHint');content.append(hint);const entries=(session.readValue('job-history')||[]).filter(i=>Date.parse(i.expires_at)>Date.now());if(!entries.length){const p=document.createElement('p');p.textContent=tr('noBuilds');content.append(p);}for(const job of entries){const row=document.createElement('section');row.className='project-manager-row';const title=document.createElement('strong');title.textContent=job.name;const info=document.createElement('p');info.className='ui-muted';info.textContent=`${new Date(job.created_at).toLocaleString(window.mpbI18n.getLanguage())} · ${t('job.'+job.status)} · ${tr('version')} ${(job.fingerprint||'').slice(0,10)}`;const result=button({key:'getBuild'},async()=>{const data=await(await api('/studio/jobs/'+job.job_id)).json();info.textContent=`${new Date(job.created_at).toLocaleString(window.mpbI18n.getLanguage())} · ${t('job.'+data.status)} · ${tr('version')} ${(job.fingerprint||'').slice(0,10)}`;remember({...job,status:data.status});if(data.status==='success'){const artifact=data.result.pdf||data.result.image;if(!artifact)throw new Error(t('invalidResponse'));MpbArchive.download(new Blob([Uint8Array.from(atob(artifact),c=>c.charCodeAt(0))],{type:data.result.pdf?'application/pdf':'image/png'}),`${MpbArchive.safePath(job.name).replaceAll('/','_')}-${job.created_at.slice(0,10)}.${data.result.pdf?'pdf':'png'}`);}else if(data.status==='error'){info.textContent+=' · '+(data.error||t('buildFailed'));}});row.append(title,info,result);content.append(row);}await MpbUI.dialog({title:tr('buildHistory'),content,actions:[{label:tr('close'),value:'close'}]});}
    async function cancelJob(){if(!activeJob)return;const id=activeJob.job_id;const response=await(await api(`/studio/jobs/${id}/cancel`,{method:'POST'})).json();if(activeJob?.job_id===id){activeJob.status=response.status;session.storeValue('active-job',activeJob);updateJobUi();if(!jobPolling)await pollJob();}}
    function errorLinks(errors,job){const list=$('studio-error-links');list.replaceChildren();for(const error of errors){const path=error.file||error.filename||error.path;const file=projectFiles.find(f=>f.path===path)||(String(job.fileId)===String(currentFileId)?currentFile():null);const line=Math.max(1,Number(error.line)||1);list.append(button(`${file?.path||path||tr('document')}:${line} — ${error.message||t('buildFailed')}`,async()=>{if(job.projectId&&String(job.projectId)!==String(currentProjectId)){await openProject(job.projectId);updateModeUi();}const target=projectFiles.find(f=>f.path===path)||projectFiles.find(f=>f.id===job.fileId)||projectFiles.find(f=>f.is_main);if(target)await openFile(target.id);if(innerWidth<768)switchMobileTab('editor-pane');if(editor.revealLineInCenter){editor.revealLineInCenter(line);editor.setPosition({lineNumber:line,column:1});editor.focus();}else{const area=$('monaco-container').querySelector('textarea');if(area){const pos=area.value.split('\n').slice(0,line-1).join('\n').length+(line>1?1:0);area.focus();area.setSelectionRange(pos,pos);}}}));}}
    function renderUploads(){const list=$('studio-upload-list');list.replaceChildren();const target=document.createElement('p');target.className='ui-muted studio-upload-hint';target.textContent=tr('uploadProject',{name:projectsList.find(p=>String(p.id)===String(uploadProjectId))?.name||String(uploadProjectId)});list.append(target);const done=uploadQueue.filter(x=>x.state==='success').length;const progress=document.createElement('progress');progress.max=uploadQueue.length||1;progress.value=done;progress.setAttribute('aria-label',tr('uploadProgress',{done,total:uploadQueue.length}));list.append(progress);for(const item of uploadQueue){const row=document.createElement('div');row.className='upload-row';const span=document.createElement('span');span.textContent=`${item.file.name} · ${tr('upload.'+item.state)}`;row.append(span);if(item.state==='error')row.append(button({key:'retry'},()=>performUploads()));list.append(row);}}
    async function performUploads(){if(uploadBusy)return;uploadBusy=true;try{await transition(async()=>{const projectId=uploadProjectId;for(const item of uploadQueue.filter(i=>i.state==='queued'||i.state==='error')){if(item.file.size>5*1024*1024){item.state='large';renderUploads();continue;}item.state='uploading';renderUploads();try{const body=new FormData();body.append('file',item.file);await api(`/studio/projects/${projectId}/upload`,{method:'POST',body});item.state='success';}catch{item.state='error';}renderUploads();}if(String(currentProjectId)===String(projectId))await activateProject(projectId);setStatus('saved');});}finally{uploadBusy=false;}}
    async function upload(files){if(!currentProjectId)throw new Error(t('chooseProject'));if(uploadBusy)throw new Error(tr('uploadWait'));uploadProjectId=currentProjectId;uploadQueue=files.map(file=>({file,state:'queued'}));renderUploads();await performUploads();}
    return {init,mode,filename,resetCreate,draft,templatePreview,manageProjects,conflict,hash,remember,errorLinks,upload};
})();
