mixed-port: 20170
allow-lan: true
mode: rule
log-level: warning

proxy-providers:
  something:
    type: http
    url: "http://127.0.0.1:8080/"
    interval: 3600
    path: ./something.yaml
    health-check:
      enable: true
      url: https://api.telegram.org
      interval: 60
      timeout: 5000
      lazy: false
      expected-status: 200-499

proxy-groups:
  - name: "AUTO-BEST-NODE"
    type: url-test
    use: [something]
    url: https://api.telegram.org
    interval: 60
    tolerance: 50
    timeout: 5000
    expected-status: 200-499

rules:
  - IP-CIDR,127.0.0.0/8,DIRECT,no-resolve
  - IP-CIDR,10.0.0.0/8,DIRECT,no-resolve
  - IP-CIDR,172.16.0.0/12,DIRECT,no-resolve
  - IP-CIDR,192.168.0.0/16,DIRECT,no-resolve
  - MATCH, AUTO-BEST-NODE
