mixed-port: 20170
allow-lan: true
mode: rule
log-level: warning
ipv6: false
external-controller: 127.0.0.1:9090
secret: ""

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:1053
  default-nameserver:
    - 8.8.8.8
    - 1.1.1.1
  nameserver:
    - 8.8.8.8
    - 1.1.1.1

proxy-providers:
  something-telegram:
    type: http
    url: "http://127.0.0.1:8080/"
    interval: 3600
    path: ./something-telegram.yaml
    health-check:
      enable: true
      url: https://api.telegram.org
      interval: 15
      timeout: 7000
      lazy: false
      expected-status: 200-499
  something-openai:
    type: http
    url: "http://127.0.0.1:8080/"
    interval: 3600
    path: ./something-openai.yaml
    health-check:
      enable: true
      url: https://api.openai.com/v1/models
      interval: 15
      timeout: 7000
      lazy: false
      expected-status: 200-499

proxy-groups:
  - name: "TELEGRAM-AUTO"
    type: url-test
    use: [something-telegram]
    url: https://api.telegram.org
    interval: 15
    tolerance: 100
    timeout: 7000
    lazy: false
    max-failed-times: 1
    expected-status: 200-499
  - name: "OPENAI-AUTO"
    type: url-test
    use: [something-openai]
    url: https://api.openai.com/v1/models
    interval: 15
    tolerance: 100
    timeout: 7000
    lazy: false
    max-failed-times: 1
    expected-status: 200-499

rules:
  - IP-CIDR,127.0.0.0/8,DIRECT,no-resolve
  - IP-CIDR,10.0.0.0/8,DIRECT,no-resolve
  - IP-CIDR,172.16.0.0/12,DIRECT,no-resolve
  - IP-CIDR,192.168.0.0/16,DIRECT,no-resolve
  - DOMAIN-SUFFIX,ruz.fa.ru,DIRECT
  - DOMAIN,api.telegram.org,TELEGRAM-AUTO
  - DOMAIN-SUFFIX,telegram.org,TELEGRAM-AUTO
  - DOMAIN-SUFFIX,t.me,TELEGRAM-AUTO
  - DOMAIN-SUFFIX,telegram.me,TELEGRAM-AUTO
  - DOMAIN-SUFFIX,telegra.ph,TELEGRAM-AUTO
  - DOMAIN-SUFFIX,chatgpt.com,OPENAI-AUTO
  - DOMAIN-SUFFIX,openai.com,OPENAI-AUTO
  - DOMAIN-SUFFIX,oaistatic.com,OPENAI-AUTO
  - DOMAIN-SUFFIX,oaiusercontent.com,OPENAI-AUTO
  - MATCH,DIRECT
